# Generated by Django 3.2.9 on 2021-12-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='appeals',
            field=models.CharField(choices=[('RQ', 'Request'), ('LT', 'Letter'), ('WS', 'Website'), ('CO', 'Company Initiative')], default='RQ', max_length=2),
        ),
    ]
