# Generated by Django 3.2.9 on 2021-12-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_email', models.EmailField(max_length=250, unique=True)),
                ('personal_pass', models.CharField(max_length=250)),
                ('personal_image', models.ImageField(blank=True, upload_to='users')),
            ],
            options={
                'verbose_name': 'cabinet',
                'verbose_name_plural': 'cabinets',
                'ordering': ('last_name',),
            },
        ),
    ]
