# Generated by Django 3.2.9 on 2021-12-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0003_auto_20211224_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'ordering': ('-created_date',),
            },
        ),
        migrations.AlterField(
            model_name='interaction',
            name='appeals',
            field=models.CharField(choices=[('AP', 'Заявка'), ('LE', 'Письмо'), ('SI', 'Сайт'), ('CO', 'Инициатива компании')], default='AP', max_length=2),
        ),
    ]
