# Generated by Django 3.2.9 on 2021-12-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0005_interaction_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
